
[package]
name = "sky_trade_land_token_program"
version = "0.0.0"
description = "Test Summary"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "sky_trade_land_token_program"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = [
    "anchor-lang/idl-build",
    "anchor-spl/idl-build",
]

[dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }
ahash = "*"
auction-house = {path = "../../../../auction-house-program/programs/auction-house/", features = ["cpi"]}
anchor-spl = "0.30.1"
mpl-bubblegum = "1.4.0"
